from random import randint

maquina = randint(1, 3)
print(maquina)
maquina = randint(1, 3)
print(maquina)
maquina = randint(1, 3)
print(maquina)
maquina = randint(1, 3)
print(maquina)
maquina = randint(1, 3)
print(maquina)
maquina = randint(1, 3)
print(maquina)
maquina = randint(1, 3)
print(maquina)
maquina = randint(1, 3)
print(maquina)
maquina = randint(1, 3)
print(maquina)
maquina = randint(1, 3)
print(maquina)
maquina = randint(1, 3)
print(maquina)
maquina = randint(1, 3)
print(maquina)
